### ISSUE TITLE
Sass Partials

### ISSUE THREAD

**Issue by rcass** [redacademy/play-winter-2018#27]
Here are some quick little things to fix in your sass partials:

- [x] Remove _fonts.scss since it is not being used

- [x] Remove import of _fonts.scss in the style.scss, since it is not being used

- [ ] Make sure all colors are being declared as variables. Ex: turn this into a variable https://github.com/redacademy/play-winter-2018/blob/19390dfdf0e780937916361da482641e45fb2ecb/themes/integrate-play/sass/_forms.scss#L145

**Comment by EricChan277** [comment]
@cchan54 @jorosafi

**Comment by jorosafi** [comment]
Hi @rcass, 

How necessary is declaring every colour as a variable? I ask because the stylesheet we were given has 13 different colours, most of which are shades of orange, purple and yellow (all three of which are already in the variables.scss). 

Most of those shades are only used once or twice for the bubbles or for hover effects. The reason I didn't create a variable for all 13 of them is because it's more work to create the variable than to just add the hex code the one or two times it comes up. 

For some of those hover effects I am also just using the darken Sass function instead of putting the exact hex code that appears on invision. 

Is it ok if we just create the variables for colours that are used repeatedly?

**Comment by rcass** [comment]
Honestly, is you start making variables for colours a good rule of thumb is just to make all other them do that. Basically, it just sets a standard that all colours will be found as variables in the variables partial. 

I understand where you are coming from though, 13 different colours and where many are only used as state colours may not be the best use of variables. Another solution would be to explore sass functions, [this](https://robots.thoughtbot.com/controlling-color-with-sass-color-functions) is a good article on it.

By using those functions you can easily slightly change the colour for all those different states (hover, active, etc) but not have too many variables. Also makes it easy to change the colour in the future in just the variable value and not need to go back and change all the hexcodes in the random spots throughout the stylesheet.

**Comment by rcass** [comment]
Oh man, I only read half of your comment before I started writting 😓 sorry about that, I can see you are already utilizing those sass functions.

But yep, just create variables for the ones you are using repeatedly, its all good
